package gateway

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"

	"github.com/miere/murtaugh/internal/llm"
	slackclient "github.com/miere/murtaugh/internal/slack/client"
	"github.com/miere/murtaugh/internal/slack/replyblock"
	"github.com/slack-go/slack"
)

// SlackSink is the reply-text delivery seam beneath the renderer (spec 021). Two
// transports implement it — streaming (StreamWriter) and buffered posting
// (bufferedSink) — and defaultSlackSink negotiates between them: it streams, and
// on the FIRST write to a surface that cannot host a Slack stream (a canvas, which
// Slack rejects with channel_type_not_supported) it downgrades once to a buffered
// chat.postMessage. The renderer drives it exactly as it drove *StreamWriter, so
// the downgrade is invisible above this seam and the canvas reply lands instead of
// erroring the whole turn.
//
// This is the handle-oriented, text-only form. The opaque-MessageRef / two-verb
// (text + task-card) generalisation lives in spec 021 §4 (AgentSlackSession);
// today only the reply-text path routes through this seam, which fixes the canvas
// bug for the default (simplified) progress mode. Tasks-mode tool cards still
// stream — that is the next slice (buffered PlanBlock cards).
type SlackSink interface {
	Append(ctx context.Context, text string) error
	Fail(ctx context.Context, err error) error
	Stop(ctx context.Context) error
	Started() bool
	Stopped() bool
}

// messagePoster is the narrow Slack surface bufferedSink needs: a single
// chat.postMessage. *slack.Client satisfies it — it is the same object wired as the
// gateway's statusMessenger — and tests substitute a fake.
type messagePoster interface {
	PostMessageContext(ctx context.Context, channelID string, options ...slack.MsgOption) (string, string, error)
}

// slackChannelTypeUnsupported is the Slack API error code returned when a surface
// (notably a canvas) cannot host a streaming message.
const slackChannelTypeUnsupported = "channel_type_not_supported"

// maxBufferedPostChars bounds a single buffered chat.postMessage. A longer reply is
// split across ordered messages. Conservative relative to Slack's hard text limit
// so a reply is never truncated.
//
// The streaming transport has the same problem and solves it the same way, at
// maxStreamMessageChars — see StreamWriter.paint. The two limits differ because
// Slack's do (a posted message and a streaming message are not capped alike), so
// they stay as separate constants rather than one shared number.
const maxBufferedPostChars = 3900

// isChannelTypeUnsupported reports whether err is Slack rejecting a stream because
// the destination surface type is unsupported (a canvas). This is the one place
// that inspects the raw Slack error — a typed match on slack.SlackErrorResponse,
// not a string sniff; everything above negotiates on this boolean.
func isChannelTypeUnsupported(err error) bool {
	var se slack.SlackErrorResponse
	return errors.As(err, &se) && se.Err == slackChannelTypeUnsupported
}

// streamFailMessage is the notice painted on the reply surface when a turn errors.
// Shared by StreamWriter.Fail and the sinks so streamed and buffered failures read
// identically.
//
// A provider failure (any agent backed by internal/llm) is classified and painted
// as a headline plus the provider's own sentence, so "Gemini is overloaded (503)"
// reaches the user instead of a wrapped Go error chain wrapped around a JSON body.
// Everything else — ACP transport faults, spawn failures, our own bugs — keeps the
// generic notice with the raw error, which is the useful thing to see for those.
func streamFailMessage(err error) string {
	if failure, ok := llm.Classify(err); ok {
		message := "\n\n:warning: *Agent is not available* — " + failure.String()
		if detail := sanitizeSlackInline(failure.Message); detail != "" {
			message += "\n" + detail
		}
		return message
	}

	message := "\n\n:warning: Murtaugh hit an error while talking to the agent."
	if err != nil {
		message += "\n`" + sanitizeSlackInline(err.Error()) + "`"
	}
	return message
}

// --- bufferedSink -----------------------------------------------------------

// bufferedSink accumulates a reply and delivers it as a single (chunked if long)
// chat.postMessage when the section is sealed. It is the fallback transport for a
// surface that cannot stream (a canvas): the reply is already fully generated by
// the time we post, so buffering loses only the incremental paint, never content.
// It never reports channel_type_not_supported — posting works everywhere streaming
// does not.
// The reply is delivered as a Block Kit `markdown` block rather than in
// chat.postMessage's `text` field, so the buffered transport reads the same
// standard-Markdown dialect the streaming one does — see internal/slack/
// replyblock for why that mattered and what it costs in mention fidelity.
type bufferedSink struct {
	poster      messagePoster
	channelID   string
	threadTS    string
	logger      *slog.Logger
	blocks      *replyblock.Renderer
	resolveName func(ctx context.Context, userID string) string

	buf     strings.Builder
	started bool
	stopped bool
}

func newBufferedSink(poster messagePoster, channelID string, opts StreamWriterOptions) *bufferedSink {
	logger := opts.Logger
	if logger == nil {
		logger = slog.Default()
	}
	return &bufferedSink{
		poster:      poster,
		channelID:   channelID,
		threadTS:    opts.ThreadTS,
		logger:      logger,
		blocks:      replyblock.NewRenderer(opts.TemplateDir, nil),
		resolveName: opts.ResolveUserName,
	}
}

// Append buffers a delta. Unlike streaming it paints nothing yet — the message is
// posted whole on Stop. An empty delta or a write after Stop is a no-op, matching
// StreamWriter so the two transports are interchangeable behind the sink.
func (b *bufferedSink) Append(_ context.Context, text string) error {
	if text == "" || b.stopped {
		return nil
	}
	b.started = true
	b.buf.WriteString(text)
	return nil
}

func (b *bufferedSink) Fail(ctx context.Context, err error) error {
	if appendErr := b.Append(ctx, streamFailMessage(err)); appendErr != nil {
		return appendErr
	}
	return b.Stop(ctx)
}

// Stop posts the accumulated reply. A section that buffered nothing (an empty text
// run) posts no message — matching streaming's no-empty-message property.
func (b *bufferedSink) Stop(ctx context.Context) error {
	if b.stopped {
		return nil
	}
	b.stopped = true
	if !b.started {
		return nil
	}
	text := strings.TrimSpace(b.buf.String())
	if text == "" {
		return nil
	}
	return b.post(ctx, text)
}

func (b *bufferedSink) Started() bool { return b.started }
func (b *bufferedSink) Stopped() bool { return b.stopped }

func (b *bufferedSink) post(ctx context.Context, text string) error {
	if b.poster == nil {
		b.logger.Warn("buffered Slack sink has no poster; dropping reply", "channel", b.channelID)
		return nil
	}
	// Split first, then rewrite each piece: mentions are scoped to the message
	// they appear in, so a long reply's first post does not ping someone named
	// only in its third. (splitForSlack breaks on newline or space, and a bare
	// `<@U123>` contains neither, so a reference cannot be severed in half. The
	// labelled `<@U123|some name>` form could be, but agents do not emit it.)
	for _, chunk := range splitForSlack(text, maxBufferedPostChars) {
		options, err := b.postOptions(ctx, chunk)
		if err != nil {
			return err
		}
		if _, _, err := b.poster.PostMessageContext(ctx, b.channelID, options...); err != nil {
			return fmt.Errorf("post buffered Slack message: %w", err)
		}
	}
	b.logger.Info("posted buffered Slack reply", "channel", b.channelID, "bytes", len(text))
	return nil
}

// postOptions builds the chat.postMessage options for one chunk: the rendered
// markdown block (plus a mention footer when the chunk tagged anyone), and the
// chunk's raw text as the notification fallback.
//
// Keeping MsgOptionText alongside the blocks is not redundancy. Slack renders
// the blocks but reads `text` for the push notification and the channel-list
// preview; dropping it degrades every mobile notification to "this content
// can't be displayed".
//
// A render or decode failure falls back to posting the text alone. That is the
// pre-block behaviour — imperfect formatting, but the reply still arrives, which
// beats failing a turn the agent has already finished.
func (b *bufferedSink) postOptions(ctx context.Context, chunk string) ([]slack.MsgOption, error) {
	options := []slack.MsgOption{slack.MsgOptionText(chunk, false)}
	if b.threadTS != "" {
		options = append(options, slack.MsgOptionTS(b.threadTS))
	}

	document := b.replyDocument(ctx, chunk)
	if document == nil {
		return options, nil
	}
	blocks, err := slackclient.DecodeBlocks(document)
	if err != nil {
		b.logger.Warn("could not decode buffered reply blocks; posting plain text", "channel", b.channelID, "error", err)
		return options, nil
	}
	return append(options, slack.MsgOptionBlocks(blocks...)), nil
}

// replyDocument renders one chunk into the raw Block Kit JSON that will be
// posted, or nil if it cannot be rendered. It is the seam the buffered
// transport's tests assert on: slack-go only folds blocks into the request at
// build time, so the document is not observable from a captured MsgOption.
func (b *bufferedSink) replyDocument(ctx context.Context, chunk string) []byte {
	rendered, mentions := replyblock.Rewrite(chunk, b.nameResolver(ctx))
	document, err := b.blocks.Render(rendered, mentions)
	if err != nil {
		b.logger.Warn("could not render buffered reply as blocks; posting plain text", "channel", b.channelID, "error", err)
		return nil
	}
	return document
}

// nameResolver adapts the configured resolver to the signature Rewrite wants,
// binding the turn's context. nil stays nil so Rewrite takes its no-resolver
// path rather than calling through a wrapper that always answers "".
func (b *bufferedSink) nameResolver(ctx context.Context) func(string) string {
	if b.resolveName == nil {
		return nil
	}
	return func(userID string) string { return b.resolveName(ctx, userID) }
}

// splitForSlack splits text into ordered pieces of at most max runes, preferring a
// newline and then a space boundary so a chunk never breaks mid-line or mid-word.
// Rune-based so a multibyte character is never split. A short text is returned as a
// single piece.
func splitForSlack(text string, max int) []string {
	runes := []rune(text)
	if max <= 0 || len(runes) <= max {
		return []string{text}
	}
	var parts []string
	for len(runes) > max {
		window := string(runes[:max])
		cut := max
		if i := strings.LastIndexByte(window, '\n'); i > 0 {
			cut = len([]rune(window[:i]))
		} else if i := strings.LastIndexByte(window, ' '); i > 0 {
			cut = len([]rune(window[:i]))
		}
		parts = append(parts, strings.TrimRight(string(runes[:cut]), " \n"))
		runes = []rune(strings.TrimLeft(string(runes[cut:]), "\n"))
	}
	if strings.TrimSpace(string(runes)) != "" {
		parts = append(parts, string(runes))
	}
	return parts
}

// --- defaultSlackSink (negotiating facade) ----------------------------------

// defaultSlackSink streams, and downgrades once to buffered posting the first time
// the destination rejects a stream (a canvas → channel_type_not_supported). Because
// the whole render loop is single-threaded per turn (see chatRenderer), the swap is
// a plain field assignment — no locking. The downgrade can only happen on the first
// write (StreamWriter.Start is lazy, so channel_type_not_supported surfaces there),
// before any content is committed, so retrying that one write on the buffered
// transport loses nothing. A transient error (network, rate-limit) is NOT a
// downgrade trigger — it surfaces unchanged so real failures are never masked.
type defaultSlackSink struct {
	streaming  SlackSink
	buffered   SlackSink
	active     SlackSink
	downgraded bool
	logger     *slog.Logger
}

func newDefaultSlackSink(api StreamAPI, poster messagePoster, channelID string, opts StreamWriterOptions, logger *slog.Logger) *defaultSlackSink {
	if logger == nil {
		logger = slog.Default()
	}
	return &defaultSlackSink{
		streaming: NewStreamWriter(api, channelID, opts),
		buffered:  newBufferedSink(poster, channelID, opts),
		active:    nil, // set to streaming below
		logger:    logger,
	}
}

func (s *defaultSlackSink) current() SlackSink {
	if s.active == nil {
		s.active = s.streaming
	}
	return s.active
}

func (s *defaultSlackSink) Append(ctx context.Context, text string) error {
	err := s.current().Append(ctx, text)
	if err != nil && !s.downgraded && isChannelTypeUnsupported(err) {
		s.downgrade()
		return s.active.Append(ctx, text)
	}
	return err
}

// Fail routes the failure notice through the downgrade-aware Append so a canvas
// surface switches to buffered posting before we paint, rather than a fresh
// stream-open erroring a second time. Otherwise mirrors StreamWriter.Fail.
func (s *defaultSlackSink) Fail(ctx context.Context, cause error) error {
	if err := s.Append(ctx, streamFailMessage(cause)); err != nil {
		return err
	}
	return s.Stop(ctx)
}

func (s *defaultSlackSink) Stop(ctx context.Context) error { return s.current().Stop(ctx) }
func (s *defaultSlackSink) Started() bool                  { return s.current().Started() }
func (s *defaultSlackSink) Stopped() bool                  { return s.current().Stopped() }

func (s *defaultSlackSink) downgrade() {
	s.active = s.buffered
	s.downgraded = true
	s.logger.Info("downgraded Slack reply to buffered post (surface cannot stream)")
}
