package sandbox

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// seatbeltProfile renders the SBPL policy for a Spec.
//
// SBPL evaluates rules IN ORDER and the LAST MATCHING RULE WINS. That single
// property is what makes "deny broadly, then carve out narrowly" expressible, and
// it is why the ordering of the sections below is load-bearing rather than
// cosmetic: the write carve-outs must follow the blanket write deny, or they are
// dead text.
func seatbeltProfile(spec Spec) (string, error) {
	var b strings.Builder

	b.WriteString("(version 1)\n")
	b.WriteString("; Generated by Murtaugh. Base posture: everything allowed, then\n")
	b.WriteString("; writes locked down to a narrow carve-out and credential stores blinded.\n")
	b.WriteString("(allow default)\n\n")

	// --- Writes: deny everything, then re-allow the agent's own surfaces. -----
	//
	// The blanket deny is what makes the box worth having. Note what it covers
	// implicitly and deliberately: Murtaugh's own config dir. A boxed agent cannot
	// rewrite agents.yaml, config.yaml or .env to widen its own permissions on the
	// next restart, which would otherwise be a trivial escape.
	b.WriteString("; --- writes: deny-by-default, narrow carve-outs below ---\n")
	b.WriteString("(deny file-write*)\n")

	writable, err := writablePaths(spec)
	if err != nil {
		return "", err
	}
	for _, w := range writable {
		fmt.Fprintf(&b, "(allow file-write* %s)\n", subpathAndLiteral(w))
	}

	// /dev must stay writable or node dies immediately: /dev/null, /dev/urandom
	// and the tty are all write operations under the blanket deny.
	b.WriteString("(allow file-write* (subpath \"/dev\"))\n")

	// --- Reads: allow-by-default, minus the credential stores. ---------------
	//
	// A read ALLOWLIST is the stricter posture and it is not what we do, on
	// purpose: a real coding agent reads compilers, toolchains, caches, git
	// objects and system headers from paths nobody enumerates correctly on the
	// first try. Deny-list keeps the agent working; it is the weaker half of the
	// box and is documented as such.
	deny := spec.DenyRead
	if deny == nil {
		deny = defaultDenyRead
	}
	if len(deny) > 0 {
		b.WriteString("\n; --- reads: allow-all minus the credential stores ---\n")
		for _, d := range deny {
			d = strings.TrimSpace(d)
			if d == "" {
				continue
			}
			fmt.Fprintf(&b, "(deny file-read* %s)\n", subpathAndLiteral(realPath(d)))
		}
	}

	return b.String(), nil
}

// writablePaths assembles the always-on writable set plus the profile's extras,
// each resolved through realPath and de-duplicated.
//
// The always-on entries are not conveniences — each one is load-bearing:
//
//	workdir        the agent's actual workspace
//	$TMPDIR, /tmp  node refuses to run without a writable temp dir
//	~/.claude      Claude Code's session state, resume history and todos
//	~/.claude.json its top-level settings file
//	bridge socket  `murtaugh mcp-bridge` dials it to serve Murtaugh's own tools;
//	               connecting to a unix socket counts as a write, and omitting it
//	               takes down the ENTIRE slack.*/jobs tool surface with no error
//	               that points at the sandbox
func writablePaths(spec Spec) ([]string, error) {
	var raw []string

	if dir := strings.TrimSpace(spec.WorkDir); dir != "" {
		raw = append(raw, dir)
	}
	if tmp := strings.TrimSpace(os.Getenv("TMPDIR")); tmp != "" {
		raw = append(raw, tmp)
	}
	raw = append(raw, "/tmp")

	if home, err := os.UserHomeDir(); err == nil && home != "" {
		raw = append(raw, filepath.Join(home, ".claude"), filepath.Join(home, ".claude.json"))
	}
	if sock := strings.TrimSpace(spec.BridgeSocket); sock != "" {
		raw = append(raw, sock)
	}
	raw = append(raw, spec.Write...)

	seen := make(map[string]bool, len(raw))
	out := make([]string, 0, len(raw))
	for _, p := range raw {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		resolved := realPath(p)
		if seen[resolved] {
			continue
		}
		seen[resolved] = true
		out = append(out, resolved)
	}
	if len(out) == 0 {
		return nil, ErrNoWritableSurface
	}
	return out, nil
}

// subpathAndLiteral renders both filter forms for a path, OR'd together in a
// single rule. SBPL treats multiple filters in one rule as a union, so this
// covers a directory (subpath) and a plain file (literal) without the caller
// having to know which it is — ~/.netrc is a file while ~/.ssh is a directory,
// and both arrive through the same config key.
func subpathAndLiteral(p string) string {
	return fmt.Sprintf("(subpath %s) (literal %s)", sbplString(p), sbplString(p))
}

// sbplString renders a Go string as an SBPL string literal. Paths containing a
// quote or backslash are pathological but must not be allowed to terminate the
// literal early and turn the rest of a path into policy text.
func sbplString(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for _, r := range s {
		if r == '"' || r == '\\' {
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	b.WriteByte('"')
	return b.String()
}
